export const feedItems = {
  firstCard: {
    id: 1,
    img: "https://i.ibb.co/XsdmR2c/1.png",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  secondCard: {
    id: 2,
    img: "https://i.etsystatic.com/22055623/r/il/be4fa4/2252981527/il_fullxfull.2252981527_jm2w.jpg",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fcf1ed",
  },
  thirdCard: {
    id: 3,
    img: "https://latina.com/wp-content/uploads/2023/06/MG_7266-credit-@totopons-scaled.jpg",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
  fourthCard: {
    id: 4,
    img: "https://i.pinimg.com/564x/27/e8/a4/27e8a47d674a3f40d2b5ac5e76c2ab6f.jpg",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
};

export const cardItems = [
  {
    id: 0,
    price: 80.99,
    text: "SHIRTS NEW ERA",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "SHIRTS",
  },
  {
    id: 1,
    price: 100.0,
    text: "JACKET BOMER",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "JACKETS",
  },
  {
    id: 2,
    price: 150.3,
    text: "JACKET WINTER LONG",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "JACKETS",
  },
  {
    id: 3,
    price: 80.99,
    text: "JACKET CASUAL",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "JACKETS",
  },
  {
    id: 4,
    price: 120.0,
    text: "JACKET WINTER SHORT",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "JACKETS",
  },
  {
    id: 5,
    price: 90.99,
    text: "CARDIGAN CASUAL",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "SWEATERS",
  },
  {
    id: 6,
    price: 90.99,
    text: "CARDIGAN CASUAL",
    colors: ["#D7D5CE", "#145A32", "#A93226"],
    imgs: ["card-model", "card-model2", "card-model3"],
    feature: "",
    category: "SWEATERS",
  },
];
